### ISSUE TITLE
"samba.sh" is not modified to "while getopts ":hc:g:i:nprs:Su:Ww:I:Ff:" opt; do"

### ISSUE THREAD

**Issue by sunlewuyou** [stuckj/samba#14]
"samba.sh" is not modified to "while getopts ":hc:g:i:nprs:Su:Ww:I:Ff:" opt; do"

**Comment by stuckj** [comment]
Strange. It must have gotten stripped from one of the automatic pulls I have setup from dperson/samba. Thanks, I just pushed a fix for it.
